//
//  StockPortfolio.h
//  StockTicker
//
//  Created by Florence Pagan on 12/4/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

@class StockItem;

@interface StockPortfolio : NSManagedObject
{
    NSMutableArray *arrItems;
}


// Saved in DB
@property (nonatomic, retain) NSString * name;
@property (nonatomic) NSTimeInterval lastRefreshed;
@property (nonatomic, retain) NSSet *items;
@property (nonatomic) int32_t indexInList;

@property (nonatomic) BOOL lastRefreshSucceeded;

// Methods not generated by CoreData


// Item management
- (StockItem*) createStockItem;
- (void) removeStockItem:(StockItem *)item;
- (void) removeStockItemByIndex:(int)index;
- (void) moveItem:(int)from toIndex:(int)to;


- (NSArray *)allStockItems;


@end


